### ISSUE TITLE
slack-vuesualizer website error messages

### ISSUE THREAD

**Issue by RedCSol** [4350pChris/slack-vuesualizer#235]
Hey there--
Thanks for your app. 

I'm trying to parse a private channel back up from `slackdump,` when I use your website I get to choose the channels (all or the private channel or the private channel attachments). All I need are the threads, but no matter what I choose I get the error **"! workspace"** and the process stops. I'm sure you don't have time to troubleshoot my particular issue, but it would be nice to have a little more feedback so I can try to figure this out on my end.

**Comment by 4350pChris** [comment]
Hey, I just had a look at the logs and it seems like something about the workspace data was empty, which MongoDB doesn't like. I tried guarding against empty data, although I cannot promise that this will fix your problem as it may be related to private channels which I have never tried importing. You're welcome to try and see if it works now.

**Comment by maxDNA** [comment]
I tried a few export and have exact same issue as well. I am using official slack export rather than slackdump.

**Comment by noisymime** [comment]
Same issue here with an official slack export

**Comment by noisymime** [comment]
Just to add, using the same export file worked fine on my own instance using docker-compose, so the issue appears to be something on the https://slack-vuesualizer.vercel.app/ instance
