### ISSUE TITLE
Group messages and Private Channels

### ISSUE THREAD

**Issue by createchange** [4350pChris/slack-vuesualizer#662]
Hi there,

This project looks great! I was reviewing it as a tool that I could use to audit activity for users where that is warranted. In looking through the results, I had a few findings:

- Group messages are not displayed
- Private channels are not displayed
- Some channels did not seem to parse correctly(?). The channel existed in the dashboard, and files that were shared were included in the files section, however no content was displayed in the channel, files or otherwise.

I was curious if these are features that you are working on, or a bug that you are aware of.

Thanks!
Jonathan

**Comment by 4350pChris** [comment]
Hey, thanks for letting me know.
* I hadn't thought of group messages. I'll have to test that when I get the time.
* For private channels, are they included in your export? Afaik you don't get them in the export using the free plan. However, I also hadn't considered this specifically, so maybe they're not handled at all. I'll have to check this too.
* As for the third, that actually sounds like a bug. You probably self-hosted this app, right? If not I could maybe have a look at my error tracing service.

**Comment by createchange** [comment]
Sounds good!

Private channels are included in my export. I have the Enterprise Select tier of Slack. I wouldn't anticipate that they would be included on the free tier. If it would be helpful, I can provide you with sanitized exports of innocuous 1:1 and group DMs.

I was indeed self-hosting. I pulled it down via Docker and spun up a Mongo DB. I can attempt to replicate it, but I don't recall seeing any explicit errors when going through the logs.

**Comment by 4350pChris** [comment]
> Sounds good!
> 
> Private channels are included in my export. I have the Enterprise Select tier of Slack. I wouldn't anticipate that they would be included on the free tier. If it would be helpful, I can provide you with sanitized exports of innocuous 1:1 and group DMs.
> 
> I was indeed self-hosting. I pulled it down via Docker and spun up a Mongo DB. I can attempt to replicate it, but I don't recall seeing any explicit errors when going through the logs.

I was hesitant to ask, but a sanitized export would be wonderful! If you could provide that it'd make it a lot easier for me to investigate.

**Comment by createchange** [comment]
> > Sounds good!
> > Private channels are included in my export. I have the Enterprise Select tier of Slack. I wouldn't anticipate that they would be included on the free tier. If it would be helpful, I can provide you with sanitized exports of innocuous 1:1 and group DMs.
> > I was indeed self-hosting. I pulled it down via Docker and spun up a Mongo DB. I can attempt to replicate it, but I don't recall seeing any explicit errors when going through the logs.
> 
> I was hesitant to ask, but a sanitized export would be wonderful! If you could provide that it'd make it a lot easier for me to investigate.

Beautiful. Do you have an email I could send to? Also, does the free workspace export have `canvases.json` included? We don't really use them (at least, that I am aware of), but I could spin up one and grab an export with that included as well.

**Comment by 4350pChris** [comment]
You can send it to slack@ennen.dev
I don't even know what canvases are but sure throw them in and I'll have a look.

Much appreciated!

**Comment by createchange** [comment]
Thanks! Sending now. I made a canvas to include in the export as well.
